import {
  mkdtemp,
  mkdir,
  readFile,
  rm,
  symlink,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, expect, it } from "vitest";

import {
  CodexEnvironmentConflict,
  configureCodexEnvironment,
  inspectCodexEnvironment,
} from "./codex-environment";

const roots: string[] = [];

afterEach(async () => {
  await Promise.all(
    roots.splice(0).map((root) => rm(root, { recursive: true, force: true })),
  );
});

it("installs the three actions once in a new Codex environment", async () => {
  const root = await temporaryRoot();

  await expect(configureCodexEnvironment(root, true)).resolves.toMatchObject({
    state: "installed",
  });
  const path = join(root, ".codex", "environments", "environment.toml");
  const first = await readFile(path, "utf8");
  expect(first).toContain('name = "Silvic Start"');
  expect(first).toContain('name = "Silvic Preview"');
  expect(first).toContain('name = "Silvic Stop"');
  expect(first).toContain('preview --plot \\"$PWD\\" --open');

  await configureCodexEnvironment(root, true);
  await expect(readFile(path, "utf8")).resolves.toBe(first);
});

it("preserves setup and unrelated actions when installing and removing", async () => {
  const root = await temporaryRoot();
  const path = await environmentFile(root);
  const original = `# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
version = 1
name = "Existing"

[setup]
script = "pnpm install"

[[actions]]
name = "Tests"
icon = "run"
command = "pnpm test"
`;
  await writeFile(path, original);

  await configureCodexEnvironment(root, true);
  const installed = await readFile(path, "utf8");
  expect(installed).toContain(original.trimEnd());
  expect(installed).toContain('name = "Silvic Preview"');

  await configureCodexEnvironment(root, false);
  await expect(readFile(path, "utf8")).resolves.toBe(original);
});

it("updates only an outdated managed block", async () => {
  const root = await temporaryRoot();
  const path = await environmentFile(root);
  await writeFile(
    path,
    `version = 1
name = "Existing"

# >>> Silvic managed Codex actions v1
[[actions]]
name = "Silvic Preview"
icon = "run"
command = "old-preview"
# <<< Silvic managed Codex actions
`,
  );

  await expect(inspectCodexEnvironment(root)).resolves.toMatchObject({
    state: "outdated",
  });
  await configureCodexEnvironment(root, true);
  const updated = await readFile(path, "utf8");
  expect(updated).toContain('name = "Existing"');
  expect(updated).not.toContain("old-preview");
  expect(updated).toContain('preview --plot \\"$PWD\\" --open');
});

it("refuses unknown versions and unmanaged duplicate action names", async () => {
  const root = await temporaryRoot();
  const path = await environmentFile(root);
  await writeFile(path, 'version = 2\nname = "Future"\n');

  await expect(configureCodexEnvironment(root, true)).rejects.toBeInstanceOf(
    CodexEnvironmentConflict,
  );

  await writeFile(
    path,
    'version = 1\nname = "Manual"\n\n[[actions]]\nname = "Silvic Start"\ncommand = "mine"\n',
  );
  await expect(inspectCodexEnvironment(root)).resolves.toMatchObject({
    state: "conflict",
  });
});

it("removes a document that contained only Silvic's generated environment", async () => {
  const root = await temporaryRoot();
  const path = join(root, ".codex", "environments", "environment.toml");
  await configureCodexEnvironment(root, true);
  await configureCodexEnvironment(root, false);

  await expect(readFile(path, "utf8")).rejects.toMatchObject({
    code: "ENOENT",
  });
});

it("will not write through a repository-provided symbolic link", async () => {
  const root = await temporaryRoot();
  const outside = await temporaryRoot();
  await symlink(outside, join(root, ".codex"));

  await expect(configureCodexEnvironment(root, true)).rejects.toBeInstanceOf(
    CodexEnvironmentConflict,
  );
  await expect(inspectCodexEnvironment(root)).resolves.toMatchObject({
    state: "conflict",
  });
});

async function temporaryRoot(): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "silvic-codex-environment-"));
  roots.push(root);
  return root;
}

async function environmentFile(root: string): Promise<string> {
  const directory = join(root, ".codex", "environments");
  await mkdir(directory, { recursive: true });
  return join(directory, "environment.toml");
}
