import { randomUUID } from "node:crypto";
import {
  lstat,
  mkdir,
  readFile,
  rename,
  rm,
  writeFile,
} from "node:fs/promises";
import { join, normalize } from "node:path";

export type CodexEnvironmentState =
  "absent" | "installed" | "outdated" | "conflict";

export interface CodexEnvironmentIntegration {
  path: string;
  state: CodexEnvironmentState;
  detail?: string;
}

export class CodexEnvironmentConflict extends Error {
  constructor(message: string) {
    super(message);
    this.name = "CodexEnvironmentConflict";
  }
}

const beginMarker = "# >>> Silvic managed Codex actions v1";
const endMarker = "# <<< Silvic managed Codex actions";
const actionNames = ["Silvic Start", "Silvic Preview", "Silvic Stop"] as const;
const packagedCli = "/Applications/Silvic.app/Contents/Resources/bin/silvic";

const managedBlock = `${beginMarker}
[[actions]]
name = "Silvic Start"
icon = "run"
command = "\\\"${packagedCli}\\\" start --plot \\"$PWD\\""

[[actions]]
name = "Silvic Preview"
icon = "run"
command = "\\\"${packagedCli}\\\" preview --plot \\"$PWD\\" --open"

[[actions]]
name = "Silvic Stop"
icon = "run"
command = "\\\"${packagedCli}\\\" stop --plot \\"$PWD\\""
${endMarker}`;

const ownedHeader = `# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
version = 1
name = "Silvic"`;

/**
 * Reconciles the one block Silvic owns while treating the rest of Codex's
 * generated environment document as opaque. This keeps the interface small:
 * callers choose the desired state, while version checks, conflict detection,
 * atomic writes, and conservative removal stay inside the module.
 */
export async function configureCodexEnvironment(
  rootPath: string,
  enabled: boolean,
): Promise<CodexEnvironmentIntegration> {
  const location = locations(rootPath);
  await assertSafeLocation(location);
  const source = await readSource(location.file);
  const status = inspectSource(location.file, source);

  if (status.state === "conflict") {
    throw new CodexEnvironmentConflict(
      status.detail ?? "The Codex environment cannot be updated safely.",
    );
  }

  if (enabled) {
    if (status.state === "installed") return status;
    const next = source.exists
      ? replaceOrAppendManagedBlock(source.contents)
      : `${ownedHeader}\n\n${managedBlock}\n`;
    await atomicWrite(location, next);
    return inspectSource(location.file, { exists: true, contents: next });
  }

  if (status.state === "absent") return status;
  const next = removeManagedBlock(source.contents);
  if (next.trim() === ownedHeader) {
    await rm(location.file);
    return { path: location.file, state: "absent" };
  }
  await atomicWrite(location, next);
  return inspectSource(location.file, { exists: true, contents: next });
}

export async function inspectCodexEnvironment(
  rootPath: string,
): Promise<CodexEnvironmentIntegration> {
  const location = locations(rootPath);
  try {
    await assertSafeLocation(location);
  } catch (error) {
    return {
      path: location.file,
      state: "conflict",
      detail: error instanceof Error ? error.message : String(error),
    };
  }
  return inspectSource(location.file, await readSource(location.file));
}

function inspectSource(
  path: string,
  source: { exists: boolean; contents: string },
): CodexEnvironmentIntegration {
  if (!source.exists) return { path, state: "absent" };
  const starts = occurrences(source.contents, beginMarker);
  const ends = occurrences(source.contents, endMarker);
  if (starts !== ends || starts > 1) {
    return {
      path,
      state: "conflict",
      detail:
        "The Codex environment contains an incomplete or duplicate Silvic managed block.",
    };
  }

  const version = source.contents.match(
    /^\s*version\s*=\s*(\d+)\s*(?:#.*)?$/m,
  )?.[1];
  if (version !== "1") {
    return {
      path,
      state: "conflict",
      detail:
        "Silvic only updates Codex local environment documents with version = 1.",
    };
  }

  if (starts === 0) {
    const duplicate = actionNames.find((name) =>
      source.contents.includes(`name = "${name}"`),
    );
    return duplicate
      ? {
          path,
          state: "conflict",
          detail: `An unmanaged action named \"${duplicate}\" already exists.`,
        }
      : { path, state: "absent" };
  }

  const range = managedRange(source.contents);
  if (!range) {
    return {
      path,
      state: "conflict",
      detail: "The Silvic managed block could not be read safely.",
    };
  }
  const outside = `${source.contents.slice(0, range.start)}${source.contents.slice(range.end)}`;
  const duplicate = actionNames.find((name) =>
    outside.includes(`name = "${name}"`),
  );
  if (duplicate) {
    return {
      path,
      state: "conflict",
      detail: `A second action named \"${duplicate}\" exists outside Silvic's managed block.`,
    };
  }
  return {
    path,
    state:
      source.contents.slice(range.start, range.end).trim() === managedBlock
        ? "installed"
        : "outdated",
  };
}

function replaceOrAppendManagedBlock(contents: string): string {
  const range = managedRange(contents);
  if (range) {
    return `${contents.slice(0, range.start)}${managedBlock}${contents.slice(range.end)}`;
  }
  return `${contents.trimEnd()}\n\n${managedBlock}\n`;
}

function removeManagedBlock(contents: string): string {
  const range = managedRange(contents);
  if (!range) return contents;
  const before = contents.slice(0, range.start).trimEnd();
  const after = contents.slice(range.end).trimStart();
  return `${[before, after].filter(Boolean).join("\n\n")}\n`;
}

function managedRange(
  contents: string,
): { start: number; end: number } | undefined {
  const start = contents.indexOf(beginMarker);
  if (start < 0) return undefined;
  const markerEnd = contents.indexOf(endMarker, start + beginMarker.length);
  if (markerEnd < 0) return undefined;
  return { start, end: markerEnd + endMarker.length };
}

function occurrences(contents: string, value: string): number {
  return contents.split(value).length - 1;
}

function locations(rootPath: string) {
  const root = normalize(rootPath);
  const codex = join(root, ".codex");
  const directory = join(codex, "environments");
  return {
    root,
    codex,
    directory,
    file: join(directory, "environment.toml"),
  };
}

async function assertSafeLocation(location: ReturnType<typeof locations>) {
  for (const path of [location.codex, location.directory, location.file]) {
    try {
      if ((await lstat(path)).isSymbolicLink()) {
        throw new CodexEnvironmentConflict(
          `Silvic will not update a Codex environment through the symbolic link ${path}.`,
        );
      }
    } catch (error) {
      if (isMissing(error)) continue;
      throw error;
    }
  }
}

async function readSource(
  path: string,
): Promise<{ exists: boolean; contents: string }> {
  try {
    return { exists: true, contents: await readFile(path, "utf8") };
  } catch (error) {
    if (isMissing(error)) return { exists: false, contents: "" };
    throw error;
  }
}

async function atomicWrite(
  location: ReturnType<typeof locations>,
  contents: string,
): Promise<void> {
  await mkdir(location.directory, { recursive: true });
  const temporary = join(
    location.directory,
    `.environment.toml.silvic-${process.pid}-${randomUUID()}.tmp`,
  );
  try {
    await writeFile(temporary, contents, "utf8");
    await rename(temporary, location.file);
  } finally {
    await rm(temporary, { force: true });
  }
}

function isMissing(error: unknown): boolean {
  return (
    error instanceof Error &&
    "code" in error &&
    (error as NodeJS.ErrnoException).code === "ENOENT"
  );
}
